### ISSUE TITLE
Replace Bulk placeholder

### ISSUE THREAD

**Issue by Tanguygab** [mfnalex/PAPI-Replace#1]
`%replace_bulk_<bulk-config>_<input>%`

Example:
in PAPI's config, you'd have
```yml
  replace:
    bulk-replacements:
      no-special-chars:
        ",": ""
        ":": ""
        "-": ""
        "_": ""
        " ": ""
        "'": ""
        ".": ""
```
`%replace_bulk_no-special-chars_Hi, I'm: Tanguy.%` would return `HiImTanguy`

from Discord
> you have access to getString, getConfigurationSection and all that stuff once you extend PlaceholderExpansion
> you can also implement Configurable and override getDefaults to set a default configuration

**Comment by mfnalex** [comment]
Thanks, this has been added in version 2.0.0, but I called it "templates" instead.
